[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "export PUPPETEER_EXECUTABLE_PATH=$(which chromium 2>/dev/null || which chromium-browser 2>/dev/null || echo '/usr/bin/chromium') && echo \"Chromium encontrado en: $PUPPETEER_EXECUTABLE_PATH\" && node .output/server/index.mjs"